version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: DB
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

#version: '3'
#
#services:
#    mysql:
#        image: mysql:latest
#        container_name: mysql_container
#        ports:
#            - "33306:3306"  # Map the MySQL container's port to your host machine
#        environment:
#            MYSQL_ROOT_PASSWORD: root5root
##            MYSQL_DATABASE: root
##            MYSQL_USER: root
##            MYSQL_PASSWORD: root5root
#        volumes:
#            - mysql_data:/var/lib/mysql  # Persist MySQL data
#
#volumes:
#    mysql_data:
